Ow_Mons_EventScript_Example::
	lock
	faceplayer
	showmonpic SPECIES_NONE, 10, 3
	playmoncry SPECIES_NONE, CRY_MODE_NORMAL
	message Ow_Mons_EventScript_Example_Text_0
	waitmoncry
	waitbuttonpress
	hidemonpic
	closemessage
	release
	end


Ow_Mons_EventScript_Machop::
	lock
	faceplayer
	showmonpic SPECIES_MACHOP, 10, 3
	playmoncry SPECIES_MACHOP, CRY_MODE_NORMAL
	message Ow_Mons_EventScript_Machop_Text_0
	waitmoncry
	waitbuttonpress
	hidemonpic
	closemessage
	release
	end


Ow_Mons_EventScript_WhitneysMiltank::
	lock
	faceplayer
	showmonpic SPECIES_MILTANK, 10, 3
	playmoncry SPECIES_MILTANK, CRY_MODE_NORMAL
	message Ow_Mons_EventScript_WhitneysMiltank_Text_0
	waitmoncry
	waitbuttonpress
	hidemonpic
	closemessage
	release
	end


Ow_Mons_EventScript_Electrike::
	lock
	faceplayer
	showmonpic SPECIES_ELECTRIKE, 10, 3
	playmoncry SPECIES_ELECTRIKE, CRY_MODE_NORMAL
	message Ow_Mons_EventScript_Electrike_Text_0
	waitmoncry
	waitbuttonpress
	hidemonpic
	closemessage
	release
	end


Ow_Mons_EventScript_Rillaboom::
	lock
	faceplayer
	showmonpic SPECIES_RILLABOOM, 10, 3
	playmoncry SPECIES_RILLABOOM, CRY_MODE_NORMAL
	message Ow_Mons_EventScript_Rillaboom_Text_0
	waitmoncry
	waitbuttonpress
	hidemonpic
	closemessage
	release
	end


Ow_Mons_EventScript_Anorith::
	lock
	faceplayer
	showmonpic SPECIES_ANORITH, 10, 3
	playmoncry SPECIES_ANORITH, CRY_MODE_NORMAL
	message Ow_Mons_EventScript_Anorith_Text_0
	waitmoncry
	waitbuttonpress
	hidemonpic
	closemessage
	release
	end


RustboroCity_Flat2_1F_EventScript_Skitty::
	lock
	faceplayer
	waitse
	showmonpic SPECIES_SKITTY, 10, 3
	playmoncry SPECIES_SKITTY, CRY_MODE_NORMAL
	message RustboroCity_Flat2_1F_EventScript_Skitty_Text_0
	waitmoncry
	waitbuttonpress
	hidemonpic
	closemessage
	release
	end


RustboroCity_House3_EventScript_Pekachu::
	lock
	faceplayer
	waitse
	showmonpic SPECIES_PIKACHU, 10, 3
	playmoncry SPECIES_PIKACHU, CRY_MODE_NORMAL
	message RustboroCity_House3_EventScript_Pekachu_Text_0
	waitmoncry
	waitbuttonpress
	hidemonpic
	closemessage
	release
	end


Ow_Mons_EventScript_Example_Text_0:
	.string "None:$"

Ow_Mons_EventScript_Machop_Text_0:
	.string "Machop: MAAACHOPP!$"

Ow_Mons_EventScript_WhitneysMiltank_Text_0:
	.string "Miltank: Moo! Moo!$"

Ow_Mons_EventScript_Electrike_Text_0:
	.string "Electrike: Elec! Trike!$"

Ow_Mons_EventScript_Rillaboom_Text_0:
	.string "Rillaboom: Rilla! Boom!$"

Ow_Mons_EventScript_Anorith_Text_0:
	.string "Anorith: Anorith!$"

RustboroCity_Flat2_1F_EventScript_Skitty_Text_0:
	.string "Skitty: Skitty!$"

RustboroCity_House3_EventScript_Pekachu_Text_0:
	.string "Pekachu: Pika, Pika.$"
