Ow_Mons_EventScript_Example::
	showmonpic SPECIES_NONE, 10, 3
	playmoncry SPECIES_NONE, CRY_MODE_NORMAL
	message Ow_Mons_EventScript_Example_Text_0
	waitmoncry
	waitbuttonpress
	hidemonpic
	closemessage
	release
	end


Ow_Mons_EventScript_WhitneysMiltank::
	showmonpic SPECIES_MILTANK, 10, 3
	playmoncry SPECIES_MILTANK, CRY_MODE_NORMAL
	message Ow_Mons_EventScript_WhitneysMiltank_Text_0
	waitmoncry
	waitbuttonpress
	hidemonpic
	closemessage
	release
	end


Ow_Mons_EventScript_Electrike::
	showmonpic SPECIES_ELECTRIKE, 10, 3
	playmoncry SPECIES_ELECTRIKE, CRY_MODE_NORMAL
	message Ow_Mons_EventScript_Electrike_Text_0
	waitmoncry
	waitbuttonpress
	hidemonpic
	closemessage
	release
	end


Ow_Mons_EventScript_Rillaboom::
	showmonpic SPECIES_RILLABOOM, 10, 3
	playmoncry SPECIES_RILLABOOM, CRY_MODE_NORMAL
	message Ow_Mons_EventScript_Rillaboom_Text_0
	waitmoncry
	waitbuttonpress
	hidemonpic
	closemessage
	release
	end


Ow_Mons_EventScript_Anorith::
	showmonpic SPECIES_ANORITH, 10, 3
	playmoncry SPECIES_ANORITH, CRY_MODE_NORMAL
	message Ow_Mons_EventScript_Anorith_Text_0
	waitmoncry
	waitbuttonpress
	hidemonpic
	closemessage
	release
	end


Ow_Mons_EventScript_Example_Text_0:
	.string "None:$"

Ow_Mons_EventScript_WhitneysMiltank_Text_0:
	.string "Miltank: Moo! Moo!$"

Ow_Mons_EventScript_Electrike_Text_0:
	.string "Electrike: Elec! Trike!$"

Ow_Mons_EventScript_Rillaboom_Text_0:
	.string "Rillaboom: Rilla! Boom!$"

Ow_Mons_EventScript_Anorith_Text_0:
	.string "Anorith: Anorith!$"
