
RustboroCity_Flat2_3F_MapScripts::
	.byte 0

RustboroCity_Flat2_3F_Text_PresidentCollectsRareStones:
	.string "DEVON's PRESIDENT likes to collect\n"
	.string "rare stones.$"

RustboroCity_Flat2_3F_Text_PresidentsSonAlsoCollectsRareStones:
	.string "I think the PRESIDENT's son also\n"
	.string "collects rare stones.$"

RustboroCity_Flat2_3F_EventScript_Woman::
	msgbox RustboroCity_Flat2_3F_EventScript_Woman_Text_0, MSGBOX_NPC
	end


RustboroCity_Flat2_3F_EventScript_DevonEmployee::
	msgbox RustboroCity_Flat2_3F_EventScript_DevonEmployee_Text_0, MSGBOX_NPC
	end


RustboroCity_Flat2_3F_EventScript_Woman_Text_0:
	.string "I heard that the President's son\n"
	.string "collects some rare stones.\p"
	.string "he says it will give some pokemon\n"
	.string "immense power, yea right! pffttt.\p$"

RustboroCity_Flat2_3F_EventScript_DevonEmployee_Text_0:
	.string "I've been working for devon corps for\n"
	.string "two years now and haven't gotten a\l"
	.string "raise yet, they will hear from me!$"
